"use client";
import { useEffect, useRef } from "react";
export const galaxies=[
{name:"LOKI66 PRIME",role:"Strategy · Compute",x:.52,y:.51,color:"#ffd59b",agents:4218,missions:112},
{name:"ANDROMEDA",role:"Research · Knowledge",x:.19,y:.26,color:"#67d5ff",agents:742,missions:12},
{name:"NEXUS CORE",role:"Coordination · Governance",x:.51,y:.16,color:"#a598ff",agents:3260,missions:48},
{name:"TRIANGULUM",role:"Multimodal · Creative",x:.83,y:.24,color:"#79cfff",agents:608,missions:9},
{name:"SOMBRERO",role:"Data · Simulation",x:.2,y:.64,color:"#c698ff",agents:1024,missions:28},
{name:"CENTAURUS A",role:"Security · Monitoring",x:.86,y:.61,color:"#ffbc88",agents:988,missions:22},
{name:"WHIRLPOOL",role:"Engineering · Automation",x:.4,y:.85,color:"#929aff",agents:896,missions:16},
{name:"PINWHEEL",role:"Science · Analysis",x:.73,y:.85,color:"#ffb5d5",agents:732,missions:14}];
type Flow={x:number;y:number;vx:number;vy:number;from:number;to:number;age:number;life:number;phase:number;trail:{x:number;y:number}[]};
export default function GalaxyMesh({paused,reduced,selected,onSelect}:{paused:boolean;reduced:boolean;selected:number;onSelect:(n:number)=>void}){
const ref=useRef<HTMLCanvasElement>(null),clock=useRef(0),labels=useRef<HTMLDivElement>(null);
useEffect(()=>{const canvas=ref.current!,c=canvas.getContext("2d");if(!c)return;const ctx:CanvasRenderingContext2D=c;let frame=0,last=0,w=1,h=1,visible=!document.hidden;const flows:Flow[]=[];
const seed=(n:number)=>{const v=Math.sin(n*127.1+311.7)*43758.5453;return v-Math.floor(v)};
const reset=(f:Flow,i:number,pos:{x:number;y:number}[])=>{f.from=i%8;f.to=i%3===0?0:(f.from+1+Math.floor(seed(i*31+7)*7))%8;if(f.to===f.from)f.to=(f.to+1)%8;const a=pos[f.from],b=pos[f.to];f.x=a.x+(seed(i+3)-.5)*10;f.y=a.y+(seed(i+8)-.5)*10;const dx=b.x-a.x,dy=b.y-a.y,l=Math.hypot(dx,dy)||1;f.vx=dx/l*13;f.vy=dy/l*13;f.age=0;f.life=4+seed(i+41)*5;f.phase=seed(i+71)*6.28;f.trail=[]};
const resize=()=>{const r=canvas.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);w=r.width;h=r.height;canvas.width=w*d;canvas.height=h*d;ctx.setTransform(d,0,0,d,0,0);draw(clock.current,0)};
function draw(t:number,dt:number){ctx.clearRect(0,0,w,h);const unit=Math.min(w,h),cycle=(1-Math.cos(t*Math.PI/9))/2,collapse=reduced?0:Math.pow(cycle,5)*.44;
const bg=ctx.createRadialGradient(w*.52,h*.5,0,w*.52,h*.5,Math.max(w,h)*.75);bg.addColorStop(0,"#07192a");bg.addColorStop(.5,"#020b15");bg.addColorStop(1,"#010409");ctx.fillStyle=bg;ctx.fillRect(0,0,w,h);
for(let i=0;i<620;i++){const x=seed(i+1)*w,y=seed(i+900)*h,s=.25+seed(i+110)*1.3;ctx.globalAlpha=.1+seed(i+300)*.5;ctx.fillStyle=i%13===0?"#ffb78a":i%7===0?"#8edfff":"#dcefff";ctx.fillRect(x,y,s,s)}ctx.globalAlpha=1;
const pos=galaxies.map((g,i)=>({x:(g.x+(.52-g.x)*collapse)*w+Math.sin(t*.11+i)*unit*.007,y:(g.y+(.51-g.y)*collapse)*h+Math.cos(t*.1+i)*unit*.009}));
pos.forEach((p,i)=>{const el=labels.current?.children[i] as HTMLElement|undefined;if(el){el.style.left=p.x+"px";el.style.top=p.y+"px"}});
ctx.globalCompositeOperation="lighter";
pos.forEach((p,i)=>{const g=galaxies[i],R=unit*(i===0?.19:.09)*(1-collapse*.38),lobes=i===0?5:3;ctx.save();ctx.translate(p.x,p.y);ctx.rotate(i*.61+t*(i===0?.035:.022));
for(let strand=0;strand<lobes;strand++){ctx.beginPath();for(let k=0;k<=90;k++){const u=k/90*Math.PI*2,a=u+strand*Math.PI*2/lobes;const warp=1+.16*Math.sin(u*3+t*.45+i),rx=R*warp,ry=R*(.56+.1*Math.cos(u*2+t*.3));const x=Math.cos(a)*rx,y=Math.sin(a)*ry*.72+Math.sin(a*2+t*.25)*R*.18;k?ctx.lineTo(x,y):ctx.moveTo(x,y)}ctx.strokeStyle=strand%2?g.color+"42":"rgba(220,245,255,.22)";ctx.lineWidth=i===0?1.05:.7;ctx.shadowBlur=10;ctx.shadowColor=g.color;ctx.stroke();ctx.shadowBlur=0}
const count=w<700?(i===0?420:180):(i===0?1050:430);for(let n=0;n<count;n++){const u=seed(n+i*1700)*Math.PI*2,strand=n%lobes,a=u+strand*Math.PI*2/lobes+t*(.035+i*.002),warp=1+.16*Math.sin(u*3+t*.45+i),rad=R*(.42+.58*seed(n+i*2200+9))*warp;const depth=Math.sin(u*2+i+n*.01),x=Math.cos(a)*rad+(seed(n+44)-.5)*R*.09,y=(Math.sin(a)*rad*.62+Math.sin(a*2+t*.25)*R*.15)+(seed(n+88)-.5)*R*.07;const z=(depth+1)/2,size=.45+z*1.7+(n%53===0?1.7:0);ctx.globalAlpha=.18+z*.68;ctx.fillStyle=n%17===0?"#ffc39b":n%5===0?g.color:"#d9f4ff";ctx.shadowBlur=n%53===0?13:0;ctx.shadowColor=ctx.fillStyle as string;ctx.beginPath();ctx.arc(x,y,size,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0}ctx.globalAlpha=1;ctx.restore()});
const target=w<700?44:92;while(flows.length<target){const f={} as Flow;reset(f,flows.length,pos);flows.push(f)}
if(dt>0&&!paused&&!reduced)flows.forEach((f,i)=>{const d=pos[f.to],dx=d.x-f.x,dy=d.y-f.y,dist=Math.hypot(dx,dy)||1;let ax=dx/dist*Math.min(36,8+dist*.025),ay=dy/dist*Math.min(36,8+dist*.025);pos.forEach((p,pi)=>{const rx=f.x-p.x,ry=f.y-p.y,d2=rx*rx+ry*ry;if(d2<80||d2>unit*unit*.08)return;const inv=1/Math.sqrt(d2),mass=.7+galaxies[pi].agents/4200,v=(pi%2?1:-1)*mass*10000/(d2+900);ax+=-ry*inv*v;ay+=rx*inv*v});let nvx=0,nvy=0,near=0;flows.forEach(o=>{if(o===f)return;const qx=o.x-f.x,qy=o.y-f.y,q2=qx*qx+qy*qy;if(q2<1800){nvx+=o.vx;nvy+=o.vy;near++}});if(near){ax+=(nvx/near-f.vx)*.16;ay+=(nvy/near-f.vy)*.16}ax+=(Math.sin(f.y*.017+t*.65+f.phase)+Math.cos(f.x*.012-t*.39))*4.6;ay+=(Math.cos(f.x*.015-t*.51+f.phase)-Math.sin(f.y*.014+t*.33))*4.6;f.vx=(f.vx+ax*dt)*Math.pow(.969,dt*60);f.vy=(f.vy+ay*dt)*Math.pow(.969,dt*60);const s=Math.hypot(f.vx,f.vy);if(s>72){f.vx=f.vx/s*72;f.vy=f.vy/s*72}f.x+=f.vx*dt;f.y+=f.vy*dt;f.age+=dt;f.trail.push({x:f.x,y:f.y});if(f.trail.length>18)f.trail.shift();if(dist<16||f.age>f.life)reset(f,i+Math.floor(t*8),pos)});
flows.forEach((f,i)=>{if(f.trail.length>1){ctx.beginPath();ctx.moveTo(f.trail[0].x,f.trail[0].y);f.trail.slice(1).forEach(p=>ctx.lineTo(p.x,p.y));ctx.strokeStyle=i%3?"rgba(91,220,255,.2)":"rgba(255,183,138,.2)";ctx.lineWidth=.65;ctx.stroke()}ctx.fillStyle=i%3?"#c8f6ff":"#ffd4b7";ctx.shadowBlur=10;ctx.shadowColor=ctx.fillStyle as string;ctx.beginPath();ctx.arc(f.x,f.y,i%9===0?1.8:1.05,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0});
ctx.globalCompositeOperation="source-over";const p=pos[selected];ctx.strokeStyle="#a8e9ff";ctx.globalAlpha=.7;ctx.setLineDash([3,7]);ctx.beginPath();ctx.arc(p.x,p.y,unit*.055,0,Math.PI*2);ctx.stroke();ctx.setLineDash([]);ctx.globalAlpha=1}
const tick=(now:number)=>{const dt=last?Math.min((now-last)/1000,.035):0;if(!paused&&!reduced&&visible){clock.current+=dt;draw(clock.current,dt)}last=now;frame=requestAnimationFrame(tick)};const ob=new ResizeObserver(resize);ob.observe(canvas);resize();const vis=()=>{visible=!document.hidden;last=0};document.addEventListener("visibilitychange",vis);if(!paused&&!reduced)frame=requestAnimationFrame(tick);return()=>{cancelAnimationFrame(frame);ob.disconnect();document.removeEventListener("visibilitychange",vis)}},[paused,reduced,selected]);
return <div className="galaxy-canvas"><canvas ref={ref} aria-label="Astra-inspired luminous particle filament galaxy network with fluid mission flow; illustrative, not live telemetry"/><div ref={labels} className="galaxy-labels">{galaxies.map((g,i)=><button key={g.name} className={selected===i?"selected":""} style={{left:g.x*100+"%",top:g.y*100+"%"}} onClick={()=>onSelect(i)}><b>{g.name}</b><strong>{g.agents.toLocaleString()} Agents</strong><small>{g.role}</small><em>{g.missions} Missions</em></button>)}</div><div className="mesh-legend"><span>✦ Filament Node</span><span>∿ Fluid Mission Flow</span><span>◌ Orbital Structure</span><span>● Nexus Core</span></div><div className="mesh-watermark">ASTRA-INSPIRED PARTICLE FILAMENTS · FLUID FLOW · ILLUSTRATIVE NEXUS</div></div>
}