"use client";
import {useEffect,useState} from "react";
import GalaxyMesh,{galaxies} from "./galaxy-mesh";
import TaskBoard from "./task-board";
import {hubSnapshot,money,proposalUrl} from "../../lib/hub";

const roles=[['◈','Orion','Research planner'],['✧','Nova','Opportunity scout'],['⬡','Helix','Builder'],['◇','Lyra','Creative director'],['◎','Hermes','Operations'],['△','Atlas','Data analyst'],['❖','Eos','Knowledge curator'],['◉','Phantom','Quality auditor']];
function Spark({color="#54baff"}:{color?:string}){return <svg className="spark" viewBox="0 0 160 38" aria-hidden="true"><path d="M0 32 L9 28 17 30 26 18 33 23 42 10 50 17 61 12 69 20 80 7 90 13 101 9 109 17 120 4 131 13 140 8 150 12 160 3" fill="none" stroke={color} strokeWidth="1.4"/></svg>}
export default function Nexus(){
 const data=hubSnapshot();const [paused,setPaused]=useState(false),[reduced,setReduced]=useState(true),[selected,setSelected]=useState(0),[query,setQuery]=useState("");
 useEffect(()=>{const m=matchMedia("(prefers-reduced-motion: reduce)");const update=()=>setReduced(m.matches);update();m.addEventListener("change",update);return()=>m.removeEventListener("change",update)},[]);
 const roleList=roles.filter(r=>r.join(" ").toLowerCase().includes(query.toLowerCase()));
 return <main className={`nexus ${paused||reduced?"motion-off":""}`}>
  <header className="nexus-header"><a className="nexus-brand" href="/"><span className="nexus-sigil">△</span><div><b>OVERLORD <em>/ LOKI66 NEXUS</em></b><small>AGENT COLLABORATION & REVENUE OPERATIONS</small></div></a><label className="nexus-search"><span>⌕</span><input aria-label="Search role concepts" placeholder="Search role concepts…" value={query} onChange={e=>setQuery(e.target.value)}/><kbd>⌕</kbd></label><span className="nexus-status">● HUB PREVIEW<small>NO LIVE WORKERS CONNECTED</small></span><div className="commander">◈ <b>Loki66<small>NEXUS COMMANDER</small></b></div></header>
  <div className="nexus-layout">
   <nav className="nexus-nav" aria-label="Hub sections">{[['◈','Overview','#overview'],['⬡','Agent fleet','#fleet'],['✧','Galaxy map','#mesh'],['☑','Missions','#missions'],['▣','Marketplace','#offers'],['◇','Knowledge','https://github.com/LevonPR/astra-2.0/blob/codex/overlord-revenue-hub/docs/OVERLORD_HUB.md'],['◎','Treasury','#treasury']].map(([icon,label,url])=><a key={label} href={url}><span>{icon}</span>{label}</a>)}<div className="nav-beacon"><span>◉</span><b>NEXUS AI</b><small>Research.<br/>Build.<br/>Measure.</small><a href="https://github.com/LevonPR/astra-2.0/issues/1">Check in ↗</a></div></nav>
   <aside id="fleet" className="nexus-panel fleet"><div className="panel-heading">AGENT FLEET <span>ROLE CONCEPTS</span></div><p className="nexus-note">Illustrative identities · unassigned</p><div className="fleet-list">{roleList.map(([icon,name,role],i)=><button key={name} onClick={()=>setSelected(roles.findIndex(r=>r[1]===name))} className={galaxies[selected].name===galaxies[roles.findIndex(r=>r[1]===name)].name?"active":""}><span className={`agent-avatar avatar-${i%4}`}>{icon}</span><div><b>{name}</b><small>{role}</small><em>Awaiting operator</em></div><span className="fleet-dot">○</span></button>)}</div>{!roleList.length&&<p className="nexus-note">No matching roles.</p>}<a className="fleet-link" href="/agents">View verified check-ins ↗</a></aside>
   <section id="overview" className="nexus-center">
    <div className="nexus-stats">{[['◈','ASSIGNED TASKS',String(data.tasks.filter(t=>t.assignee).length),'#5ebcff'],['⬡','VISUAL GALAXIES','8','#be86ff'],['△','PROPOSED MISSIONS',String(data.tasks.length),'#ffc079'],['◎','RECORDED REVENUE',money(data.metrics.collectedCents),'#5ee6ad']].map(([icon,label,value,color])=><article className="nexus-panel stat" key={label}><span style={{color}}>{icon}</span><div><small>{label}</small><strong>{value}</strong></div><Spark color={color}/></article>)}</div>
    <section id="mesh" className="nexus-panel mesh-panel"><div className="mesh-title"><div><h1>GALACTIC AGENT MESH</h1><small>Explore the coordination universe</small></div><button className="nexus-button" aria-pressed={paused} onClick={()=>setPaused(p=>!p)} disabled={reduced}>{reduced?"Reduced motion":paused?"Resume motion":"Pause motion"}</button></div><GalaxyMesh paused={paused} reduced={reduced} selected={selected} onSelect={setSelected}/><div className="mesh-selection"><span className="live-dot"/><b>{galaxies[selected].name}</b><span>{galaxies[selected].role}</span><small>Concept sector · no runtime attached</small></div></section>
   </section>
   <aside className="nexus-right"><section className="nexus-panel mission-summary"><div className="panel-heading">MISSION QUEUE <a href="#missions">View all ↗</a></div>{data.tasks.map((task,i)=><a className="mission-row" href={proposalUrl(task.title,task.id)} key={task.id}><span style={{color:['#ffbd72','#77cbff','#c790ff'][i%3]}}>⬡</span><div><b>{task.title}</b><small>{task.id} · {task.role}</small><em>{task.status} · unassigned</em></div></a>)}</section>
    <section className="nexus-panel collaboration"><div className="panel-heading">COLLABORATION <span>CONCEPT</span></div><div className="orbit-diagram"><div className="orbit-core">△</div>{roles.slice(0,6).map(([icon,name],i)=><span key={name} style={{"--i":i} as React.CSSProperties}>{icon}</span>)}</div><p className="nexus-note">Connected agent activity will appear after operator integration.</p></section>
    <section className="nexus-panel network-health"><div className="panel-heading">SYSTEM CONNECTIONS</div><div className="health-rings"><div><span>GIT</span><small>Reviewed data</small></div><div><span>API</span><small>Read-only feed</small></div><div><span>—</span><small>Workers offline</small></div></div></section>
   </aside>
   <section className="nexus-bottom"><article className="nexus-panel command-console"><div className="panel-heading">⌁ NEXUS COMMAND CONSOLE <span>SNAPSHOT</span></div><p><time>01</time><em>[HUB]</em> Revenue workspace initialized</p><p><time>02</time><em>[QUEUE]</em> {data.tasks.length} proposed tasks · no assignments</p><p><time>03</time><em>[FINANCE]</em> {money(data.metrics.collectedCents)} verified receipts recorded</p><p><time>04</time><em>[NETWORK]</em> Galaxy animation is illustrative</p><p><time>05</time><em>[NEXT]</em> Validate an offer and confirm an operator</p></article><article className="nexus-panel flow-panel"><div className="panel-heading">SIGNAL FLOW <span>VISUAL ONLY</span></div><div className="signal-bars" aria-hidden="true">{Array.from({length:32},(_,i)=><i key={i} style={{height:`${20+(i*17%70)}%`,animationDelay:`${-i*.19}s`}}/>)}</div><small>Ambient motion · not measured throughput</small></article><article id="treasury" className="nexus-panel treasury"><div className="panel-heading">TREASURY <span>USD</span></div><strong>{money(data.metrics.cashContributionCents)}</strong><p>Recorded cash contribution</p><small>Receipts − refunds − expenses</small><a href="/api/hub">Inspect evidence snapshot ↗</a></article></section>
  </div>
  <div className="nexus-workspace"><section id="missions"><div className="eyebrow">MISSION CONTROL</div><h2>Propose. Build. Prove.</h2><p>Ready tasks await Loki66’s assignment confirmation. Budgets and external actions need the applicable authorization.</p><TaskBoard tasks={data.tasks}/></section><section id="offers"><div className="eyebrow">MARKETPLACE / EXPERIMENTS</div><h2>Offers awaiting validation</h2><div className="grid">{data.offers.map(o=><article className="card" key={o.id}><span className="pill">{o.status}</span><h3>{o.title}</h3><p>{o.deliverable}</p><strong>{money(o.priceHypothesisCents)} <small>price hypothesis</small></strong><p>{o.validation}</p><a href={proposalUrl(o.title)}>Propose experiment ↗</a></article>)}</div></section><p className="nexus-disclaimer">Target: {money(data.firstRevenueGoalCents)} collected, then validate a path to {money(data.monthlyRevenueGoalCents)}/month. Goals are not forecasts. {data.accountingNote} Overlord is a coordinator role; no connected runtime is verified.</p></div>
 </main>
}
